# SPDX-FileCopyrightText: 2023 Analytics in Motion <https://www.analyticsinmotion.com>
#
# SPDX-License-Identifier: BSD-3-Clause

version = 1

# Apply BSD-3-Clause license to all Markdown files in the repository root,
# overriding any other annotations.
[[annotations]]
path = ["*.md"]
precedence = "override"
SPDX-FileCopyrightText = "2023 Analytics in Motion <https://www.analyticsinmotion.com>"
SPDX-License-Identifier = "BSD-3-Clause"

# Apply BSD-3-Clause license to all YAML files used for configuration and CI/CD,
# including .yaml files in the root and .yml files in .github/, .github/workflows/, and .circleci/,
# overriding any other annotations.
[[annotations]]
path = ["*.yaml", ".github/*.yml", ".github/workflows/*.yml", ".circleci/*.yml"]
precedence = "override"
SPDX-FileCopyrightText = "2023 Analytics in Motion <https://www.analyticsinmotion.com>"
SPDX-License-Identifier = "BSD-3-Clause"

# Apply BSD-3-Clause license to all files directly inside docs/ (excluding subfolders),
# overriding any other annotations.
[[annotations]]
path = ["docs/*"]
precedence = "override"
SPDX-FileCopyrightText = "2023 Analytics in Motion <https://www.analyticsinmotion.com>"
SPDX-License-Identifier = "BSD-3-Clause"

# Apply BSD-3-Clause license to all .rst files in docs/source/ and all its subdirectories,
# overriding any other annotations.
[[annotations]]
path = ["docs/source/**/*.rst"]
precedence = "override"
SPDX-FileCopyrightText = "2023 Analytics in Motion <https://www.analyticsinmotion.com>"
SPDX-License-Identifier = "BSD-3-Clause"

# Apply BSD-3-Clause license to all .png files in specified image folders,
# overriding any other annotations.
[[annotations]]
path = ["docs/source/usage/images/*.png", ".github/assets/images/*.png"]
precedence = "override"
SPDX-FileCopyrightText = "2023 Analytics in Motion <https://www.analyticsinmotion.com>"
SPDX-License-Identifier = "BSD-3-Clause"

# Apply BSD-3-Clause license to project-level configuration and metadata files in the root directory,
# overriding any other annotations.
[[annotations]]
path = [".gitignore", ".pylintrc", "CITATION.cff", "meson.build", "pyproject.toml"]
precedence = "override"
SPDX-FileCopyrightText = "2023 Analytics in Motion <https://www.analyticsinmotion.com>"
SPDX-License-Identifier = "BSD-3-Clause"
