# SPDX-FileCopyrightText: 2023 Analytics in Motion <https://www.analyticsinmotion.com>
# SPDX-License-Identifier: BSD-3-Clause

"""
This module will handle the exceptions for this package.
"""

from .metrics import metrics


def error_handler(reference, hypothesis):
    """
    This function provides the overall wrapper to handle exceptions within this package.

    Parameters
    ----------
    reference : str, list or numpy array
        The ground truth transcription of a recorded speech or the expected output of a live speech.
    hypothesis : str, list or numpy array
        The text generated by a speech-to-text algorithm/system which will be compared to the reference text.

    Raises
    ------
    ValueError
        if the two input parameters do not contain the same amount of elements.
    AttributeError
        if input text is not a string, list or np.ndarray data type.
    ZeroDivisionError
        if input in reference is blank or both reference and hypothesis are empty.

    Returns
    -------
    list[Result] or Result
        This function will return either a single `Result` object or a list of `Result` objects, depending on the input.
    """
    try:
        if isinstance(reference, str) and isinstance(hypothesis, str):
            reference = [reference]
            hypothesis = [hypothesis]
        return metrics(reference, hypothesis)
    except ValueError as exc:
        raise ValueError(
            "The Reference and Hypothesis input parameters must have the same number of elements."
        ) from exc
    except AttributeError as exc:
        raise AttributeError(
            "All text should be in a string format. Please check your input does not include any "
            "Numeric data types."
        ) from exc
    except ZeroDivisionError as exc:
        raise ZeroDivisionError(
            "Invalid input: reference must not be blank, and reference and hypothesis cannot both be empty."
        ) from exc
