# SPDX-FileCopyrightText: 2023 Analytics in Motion <https://www.analyticsinmotion.com>
# SPDX-License-Identifier: BSD-3-Clause

import numpy as np
from numpy.typing import NDArray

from .errorhandler import TextInput

def calculations(reference: str, hypothesis: str) -> NDArray[np.object_]: ...
def metrics(reference: TextInput, hypothesis: TextInput) -> NDArray[np.object_]: ...
def calculations_fast(reference: str, hypothesis: str) -> NDArray[np.float64]: ...
def metrics_fast(reference: TextInput, hypothesis: TextInput) -> NDArray[np.float64]: ...
def calculations_wer_only(reference: str, hypothesis: str) -> NDArray[np.float64]: ...
def metrics_wer_only(reference: TextInput, hypothesis: TextInput) -> NDArray[np.float64]: ...
