# SPDX-FileCopyrightText: 2023 Analytics in Motion <https://www.analyticsinmotion.com>
# SPDX-License-Identifier: BSD-3-Clause

"""
This module provides a function for calculating a list of the Word Error Rates for each of the reference and
hypothesis texts.

This module defines the following function:
    - wers(reference, hypothesis)
"""

from typing import cast, overload

import numpy as np
from .errorhandler import TextBatch, TextInput, error_handler
from .metrics import metrics_wer_only


@overload
def wers(reference: str, hypothesis: str) -> float | None: ...


@overload
def wers(reference: TextBatch, hypothesis: TextBatch) -> list[float] | None: ...


def wers(reference: TextInput, hypothesis: TextInput) -> float | list[float] | None:
    """
    This function calculates a list of the Word Error Rates for each of the reference and hypothesis texts.

    Parameters
    ----------
    reference : str, list or numpy array
        The ground truth transcription of a recorded speech or the expected output of a live speech.
    hypothesis : str, list or numpy array
        The text generated by a speech-to-text algorithm/system which will be compared to the reference text.

    Returns
    -------
    float, list, or None
        This function will return either a single Word Error Rate (if the input is a pair of strings) or a list of Word
        Error Rates (if the input is a pair of lists) for each of the reference and hypothesis texts.
        If the input is invalid, the function prints a message describing the problem and returns None.

    Example
    --------
    >>> ref = ['no one else could claim that','she cited multiple reasons why']
    >>> hyp = ['no one else could claim that','she sighted multiple reasons why']
    >>> wers_example_1 = wers(ref, hyp)
    >>> print(wers_example_1)
    [0.0, 0.2]
    """
    try:
        error_handler(reference, hypothesis)
        result = metrics_wer_only(reference, hypothesis)
    except (ValueError, AttributeError, ZeroDivisionError) as err:
        print(f"{type(err).__name__}: {str(err)}")
        return None

    # Batch: (n, 3) float64, columns [wer, ld, m]
    if isinstance(result, np.ndarray) and result.ndim == 2:
        return cast(list[float], result[:, 0].tolist())  # Return wer column

    # Single: (3,) float64, WER is at index 0
    return float(result[0])
