# SPDX-FileCopyrightText: 2023 Analytics in Motion <https://www.analyticsinmotion.com>
# SPDX-License-Identifier: BSD-3-Clause
---
name: REUSE Compliance Check

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
  #    branches: [ "main" ]
    # Schedule the workflow to trigger at a specified time each day using a CRON expression
    # schedule:
      #        ┌───────────── minute (0 - 59)
      #        │  ┌───────────── hour (0 - 23)
      #        │  │ ┌───────────── day of the month (1 - 31)
      #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
      #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
      #        │  │ │ │ │
      # - cron: '25 0 * * *'  # Runs at 12:25am UTC every day
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
  contents: read

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 #v5.0.0
        